### ISSUE TITLE
ImportError: cannot import name 'OpenGLMathTex' from 'manim.opengl' 

### ISSUE THREAD

**Issue by liyangbit** [raghavg123/chanim#19]
ImportError: cannot import name 'OpenGLMathTex' from 'manim.opengl' 

In Manim Community v0.14.0,there is no 'OpenGLMathTex'  from 'manim.opengl' , how to solve this question, thx!

```python
Manim Community v0.14.0

Traceback (most recent call last):
  File "/Users/lemon/opt/anaconda3/envs/manimce/bin/manim", line 8, in <module>
    sys.exit(main())
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/manim/cli/render/commands.py", line 136, in render
    for SceneClass in scene_classes_from_file(file):
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/manim/utils/module_ops.py", line 125, in scene_classes_from_file
    module = get_module(file_path)
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/manim/utils/module_ops.py", line 50, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/lemon/Documents/animation/ManimCE/chemistry.py", line 9, in <module>
    from chanim import *
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/chanim/__init__.py", line 8, in <module>
    from .chem_objects import *
  File "/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/chanim/chem_objects.py", line 22, in <module>
    from manim.opengl import OpenGLMathTex
ImportError: cannot import name 'OpenGLMathTex' from 'manim.opengl' (/Users/lemon/opt/anaconda3/envs/manimce/lib/python3.9/site-packages/manim/opengl/__init__.py)
```

**Comment by asarigun** [comment]
I have the same issue, too.

**Comment by 0tickpulse** [comment]
same

**Comment by kilacoda-old** [comment]
Was fixed in #17 (thanks @Afostyrio!). Pushed a release to PyPI, so please try updating and see if the problem persists.
